  name: Dendron

  on:
    push:
      branches:
      - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Retain Node modules across builds
      - name: Restore Node modules cache
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            .next/node_modules
          key: node-modules-${{ hashFiles('yarn.lock')}}

      - name: Install npm dependencies
        run: yarn

      - name: Initialze workspace
        run: yarn dendron workspace init

      - name: Initialize .next
        run: yarn dendron publish init

      - name: Export notes
        run: yarn dendron publish export --target github

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: docs/
          force_orphan: true
